/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAcceptInviteRouteImport } from './routes/_app/accept-invite'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppConnectionsIndexRouteImport } from './routes/_app/connections/index'
import { Route as AppPlaygroundIndexRouteImport } from './routes/_app/playground/index'
import { Route as AppRegistryIndexRouteImport } from './routes/_app/registry/index'
import { Route as AppWorkspacesIndexRouteImport } from './routes/_app/workspaces/index'
import { Route as AppWorkspacesWorkspaceIdRouteImport } from './routes/_app/workspaces/$workspaceId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAcceptInviteRoute = AppAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsIndexRoute = AppConnectionsIndexRouteImport.update({
  id: '/connections/',
  path: '/connections/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaygroundIndexRoute = AppPlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistryIndexRoute = AppRegistryIndexRouteImport.update({
  id: '/registry/',
  path: '/registry/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesIndexRoute = AppWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesWorkspaceIdRoute =
  AppWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accept-invite': typeof AppAcceptInviteRoute
  '/settings': typeof AppSettingsRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/connections/': typeof AppConnectionsIndexRoute
  '/playground/': typeof AppPlaygroundIndexRoute
  '/registry/': typeof AppRegistryIndexRoute
  '/workspaces/': typeof AppWorkspacesIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accept-invite': typeof AppAcceptInviteRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/connections': typeof AppConnectionsIndexRoute
  '/playground': typeof AppPlaygroundIndexRoute
  '/registry': typeof AppRegistryIndexRoute
  '/workspaces': typeof AppWorkspacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/accept-invite': typeof AppAcceptInviteRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/_app/connections/': typeof AppConnectionsIndexRoute
  '/_app/playground/': typeof AppPlaygroundIndexRoute
  '/_app/registry/': typeof AppRegistryIndexRoute
  '/_app/workspaces/': typeof AppWorkspacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/accept-invite'
    | '/settings'
    | '/workspaces/$workspaceId'
    | '/connections/'
    | '/playground/'
    | '/registry/'
    | '/workspaces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/accept-invite'
    | '/settings'
    | '/'
    | '/workspaces/$workspaceId'
    | '/connections'
    | '/playground'
    | '/registry'
    | '/workspaces'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/_app/accept-invite'
    | '/_app/settings'
    | '/_app/'
    | '/_app/workspaces/$workspaceId'
    | '/_app/connections/'
    | '/_app/playground/'
    | '/_app/registry/'
    | '/_app/workspaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accept-invite': {
      id: '/_app/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AppAcceptInviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections/': {
      id: '/_app/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof AppConnectionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playground/': {
      id: '/_app/playground/'
      path: '/playground'
      fullPath: '/playground/'
      preLoaderRoute: typeof AppPlaygroundIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/registry/': {
      id: '/_app/registry/'
      path: '/registry'
      fullPath: '/registry/'
      preLoaderRoute: typeof AppRegistryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces/': {
      id: '/_app/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AppWorkspacesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces/$workspaceId': {
      id: '/_app/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAcceptInviteRoute: typeof AppAcceptInviteRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWorkspacesWorkspaceIdRoute: typeof AppWorkspacesWorkspaceIdRoute
  AppConnectionsIndexRoute: typeof AppConnectionsIndexRoute
  AppPlaygroundIndexRoute: typeof AppPlaygroundIndexRoute
  AppRegistryIndexRoute: typeof AppRegistryIndexRoute
  AppWorkspacesIndexRoute: typeof AppWorkspacesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcceptInviteRoute: AppAcceptInviteRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppWorkspacesWorkspaceIdRoute: AppWorkspacesWorkspaceIdRoute,
  AppConnectionsIndexRoute: AppConnectionsIndexRoute,
  AppPlaygroundIndexRoute: AppPlaygroundIndexRoute,
  AppRegistryIndexRoute: AppRegistryIndexRoute,
  AppWorkspacesIndexRoute: AppWorkspacesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
